import { Inter } from "next/font/google";
import "./globals.css";
import { CryptoCommuteProvider } from "../../context/cryptocommuteContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CryptoCommute",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <CryptoCommuteProvider>
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
    </CryptoCommuteProvider>
  );
}
